// scripts/update-patterns.ts
import { connectToDatabase } from '../lib/mongodb';
import { VulnerabilityPattern } from '../models/VulnerabilityPattern';

// Definição dos padrões baseada no arquivo fornecido
const PATTERNS = [
  // 1. Injection
  {
    name: 'SQL Injection (concatenação) - C#',
    queryPattern: 'ext:cs AND ("SELECT " OR "UPDATE " OR "DELETE " OR "INSERT ") AND "+"',
    category: 'Injeção SQL',
    severity: 'critical',
    description: 'Concatenação de strings em consultas SQL em C#',
    externalId: 'OWASP A03:2021',
    externalLink: 'https://owasp.org/Top10/A03_2021-Injection/',
    reference: 'OWASP Top 10 2021 - A3: Injection',
    slaHours: 4,
  },
  {
    name: 'SQL Injection (concatenação) - Java',
    queryPattern: 'ext:java AND ("executeQuery" OR "createStatement") AND "+"',
    category: 'Injeção SQL',
    severity: 'critical',
    description: 'Concatenação de strings em consultas SQL em Java',
    externalId: 'OWASP A03:2021',
    externalLink: 'https://owasp.org/Top10/A03_2021-Injection/',
    reference: 'OWASP Top 10 2021 - A3: Injection',
    slaHours: 4,
  },
  {
    name: 'SQL Injection (String.Format) - C#',
    queryPattern: '"String.Format(\\"SELECT"',
    category: 'Injeção SQL',
    severity: 'critical',
    description: 'Uso de String.Format para montar consultas SQL em C#',
    externalId: 'OWASP A03:2021',
    externalLink: 'https://owasp.org/Top10/A03_2021-Injection/',
    reference: 'OWASP Top 10 2021 - A3: Injection',
    slaHours: 4,
  },
  {
    name: 'SQL Injection (template strings) - JavaScript/TypeScript',
    queryPattern: 'ext:js OR ext:ts AND "SELECT " AND "${"',
    category: 'Injeção SQL',
    severity: 'critical',
    description: 'Concatenação de strings com template literals em consultas SQL',
    externalId: 'OWASP A03:2021',
    externalLink: 'https://owasp.org/Top10/A03_2021-Injection/',
    reference: 'OWASP Top 10 2021 - A3: Injection',
    slaHours: 4,
  },
  {
    name: 'Command Injection - C#',
    queryPattern: 'ext:cs AND "Process.Start("',
    category: 'Injeção de Comandos',
    severity: 'critical',
    description: 'Execução de comandos do sistema operacional com entradas não tratadas em C#',
    externalId: 'OWASP A03:2021',
    externalLink: 'https://owasp.org/Top10/A03_2021-Injection/',
    reference: 'OWASP Top 10 2021 - A3: Injection',
    slaHours: 4,
  },
  {
    name: 'Command Injection - Java',
    queryPattern: 'ext:java AND "Runtime.getRuntime().exec("',
    category: 'Injeção de Comandos',
    severity: 'critical',
    description: 'Execução de comandos do sistema operacional com entradas não tratadas em Java',
    externalId: 'OWASP A03:2021',
    externalLink: 'https://owasp.org/Top10/A03_2021-Injection/',
    reference: 'OWASP Top 10 2021 - A3: Injection',
    slaHours: 4,
  },
  {
    name: 'Command Injection - Python',
    queryPattern: 'ext:py AND ("os.system(" OR "subprocess.call(" OR "subprocess.Popen(")',
    category: 'Injeção de Comandos',
    severity: 'critical',
    description: 'Execução de comandos do sistema operacional com entradas não tratadas em Python',
    externalId: 'OWASP A03:2021',
    externalLink: 'https://owasp.org/Top10/A03_2021-Injection/',
    reference: 'OWASP Top 10 2021 - A3: Injection',
    slaHours: 4,
  },
  {
    name: 'Command Injection - Node.js',
    queryPattern: 'ext:js AND ("child_process" AND ("exec(" OR "spawn("))',
    category: 'Injeção de Comandos',
    severity: 'critical',
    description: 'Execução de comandos do sistema operacional com entradas não tratadas em Node.js',
    externalId: 'OWASP A03:2021',
    externalLink: 'https://owasp.org/Top10/A03_2021-Injection/',
    reference: 'OWASP Top 10 2021 - A3: Injection',
    slaHours: 4,
  },

  // 2. Cryptographic Failures
  {
    name: 'Hardcoded Password/Secret - Geral',
    queryPattern: '"password = " OR "pwd = " OR "secret = "',
    category: 'Segredos Hardcoded',
    severity: 'critical',
    description: 'Senhas ou chaves de API hardcoded no código fonte',
    externalId: 'OWASP A02:2021',
    externalLink: 'https://owasp.org/Top10/A02_2021-Cryptographic_Failures/',
    reference: 'OWASP Top 10 2021 - A2: Cryptographic Failures',
    slaHours: 4,
  },
  {
    name: 'Hardcoded API Key/Token',
    queryPattern: '"api_key" OR "apikey" OR "access_token"',
    category: 'Segredos Hardcoded',
    severity: 'critical',
    description: 'Chaves de API ou tokens de acesso hardcoded',
    externalId: 'OWASP A02:2021',
    externalLink: 'https://owasp.org/Top10/A02_2021-Cryptographic_Failures/',
    reference: 'OWASP Top 10 2021 - A2: Cryptographic Failures',
    slaHours: 4,
  },
  {
    name: 'Hardcoded Connection String - Config files',
    queryPattern: 'file:appsettings.json OR file:web.config AND "User ID=" AND "Password="',
    category: 'Segredos Hardcoded',
    severity: 'critical',
    description: 'Strings de conexão com senhas em arquivos de configuração',
    externalId: 'OWASP A02:2021',
    externalLink: 'https://owasp.org/Top10/A02_2021-Cryptographic_Failures/',
    reference: 'OWASP Top 10 2021 - A2: Cryptographic Failures',
    slaHours: 4,
  },
  {
    name: 'JWT Hardcoded',
    queryPattern: '"Bearer eyJ"',
    category: 'Segredos Hardcoded',
    severity: 'high',
    description: 'Token JWT hardcoded no código fonte',
    externalId: 'OWASP A02:2021',
    externalLink: 'https://owasp.org/Top10/A02_2021-Cryptographic_Failures/',
    reference: 'OWASP Top 10 2021 - A2: Cryptographic Failures',
    slaHours: 8,
  },
  {
    name: 'Private Key Hardcoded',
    queryPattern: '"BEGIN RSA PRIVATE KEY" OR "BEGIN PRIVATE KEY"',
    category: 'Segredos Hardcoded',
    severity: 'critical',
    description: 'Chaves privadas RSA ou outras hardcoded',
    externalId: 'OWASP A02:2021',
    externalLink: 'https://owasp.org/Top10/A02_2021-Cryptographic_Failures/',
    reference: 'OWASP Top 10 2021 - A2: Cryptographic Failures',
    slaHours: 4,
  },
  {
    name: 'Weak Hashing (MD5) - C#',
    queryPattern: 'ext:cs AND "MD5.Create()"',
    category: 'Criptografia Fraca',
    severity: 'high',
    description: 'Uso de MD5 para hashing em C#',
    externalId: 'OWASP A02:2021',
    externalLink: 'https://owasp.org/Top10/A02_2021-Cryptographic_Failures/',
    reference: 'OWASP Top 10 2021 - A2: Cryptographic Failures',
    slaHours: 24,
  },
  {
    name: 'Weak Hashing (SHA1) - C#',
    queryPattern: 'ext:cs AND "SHA1.Create()"',
    category: 'Criptografia Fraca',
    severity: 'high',
    description: 'Uso de SHA1 para hashing em C#',
    externalId: 'OWASP A02:2021',
    externalLink: 'https://owasp.org/Top10/A02_2021-Cryptographic_Failures/',
    reference: 'OWASP Top 10 2021 - A2: Cryptographic Failures',
    slaHours: 24,
  },
  {
    name: 'Weak Encryption (DES) - C#',
    queryPattern: 'ext:cs AND "DESCryptoServiceProvider"',
    category: 'Criptografia Fraca',
    severity: 'high',
    description: 'Uso de DES para criptografia em C#',
    externalId: 'OWASP A02:2021',
    externalLink: 'https://owasp.org/Top10/A02_2021-Cryptographic_Failures/',
    reference: 'OWASP Top 10 2021 - A2: Cryptographic Failures',
    slaHours: 24,
  },
  {
    name: 'Weak Hashing (MD5/SHA1) - Java',
    queryPattern: 'ext:java AND ("MessageDigest.getInstance(\\"MD5\\")" OR "MessageDigest.getInstance(\\"SHA-1\\")")',
    category: 'Criptografia Fraca',
    severity: 'high',
    description: 'Uso de MD5 ou SHA1 para hashing em Java',
    externalId: 'OWASP A02:2021',
    externalLink: 'https://owasp.org/Top10/A02_2021-Cryptographic_Failures/',
    reference: 'OWASP Top 10 2021 - A2: Cryptographic Failures',
    slaHours: 24,
  },
  {
    name: 'Weak Hashing (MD5) - Python',
    queryPattern: 'ext:py AND "hashlib.md5("',
    category: 'Criptografia Fraca',
    severity: 'high',
    description: 'Uso de MD5 para hashing em Python',
    externalId: 'OWASP A02:2021',
    externalLink: 'https://owasp.org/Top10/A02_2021-Cryptographic_Failures/',
    reference: 'OWASP Top 10 2021 - A2: Cryptographic Failures',
    slaHours: 24,
  },

  // 3. Security Misconfiguration
  {
    name: 'CORS Permissivo (Wildcard)',
    queryPattern: '"Access-Control-Allow-Origin" AND "*"',
    category: 'Configuração Incorreta',
    severity: 'medium',
    description: 'CORS configurado com wildcard (*) permitindo origens não autorizadas',
    externalId: 'OWASP A05:2021',
    externalLink: 'https://owasp.org/Top10/A05_2021-Security_Misconfiguration/',
    reference: 'OWASP Top 10 2021 - A5: Security Misconfiguration',
    slaHours: 48,
  },
  {
    name: 'CORS Permissivo (.NET)',
    queryPattern: '"AllowAnyOrigin()" OR "AllowAnyMethod()" OR "AllowAnyHeader()"',
    category: 'Configuração Incorreta',
    severity: 'medium',
    description: 'CORS excessivamente permissivo em aplicações .NET',
    externalId: 'OWASP A05:2021',
    externalLink: 'https://owasp.org/Top10/A05_2021-Security_Misconfiguration/',
    reference: 'OWASP Top 10 2021 - A5: Security Misconfiguration',
    slaHours: 48,
  },
  {
    name: 'Debug Mode Ativo (web.config)',
    queryPattern: 'file:web.config AND "debug=\\"true\\""',
    category: 'Configuração Incorreta',
    severity: 'medium',
    description: 'Modo de debug ativado em ambiente de produção (web.config)',
    externalId: 'OWASP A05:2021',
    externalLink: 'https://owasp.org/Top10/A05_2021-Security_Misconfiguration/',
    reference: 'OWASP Top 10 2021 - A5: Security Misconfiguration',
    slaHours: 48,
  },
  {
    name: 'Debug Mode Ativo (Python)',
    queryPattern: 'ext:py AND "DEBUG = True"',
    category: 'Configuração Incorreta',
    severity: 'medium',
    description: 'Modo de debug ativado em aplicações Python',
    externalId: 'OWASP A05:2021',
    externalLink: 'https://owasp.org/Top10/A05_2021-Security_Misconfiguration/',
    reference: 'OWASP Top 10 2021 - A5: Security Misconfiguration',
    slaHours: 48,
  },
  {
    name: 'Spring Boot Actuator Exposto',
    queryPattern: 'file:application.properties AND "management.endpoints.web.exposure.include=*"',
    category: 'Configuração Incorreta',
    severity: 'medium',
    description: 'Spring Boot Actuator endpoints expostos sem restrição',
    externalId: 'OWASP A05:2021',
    externalLink: 'https://owasp.org/Top10/A05_2021-Security_Misconfiguration/',
    reference: 'OWASP Top 10 2021 - A5: Security Misconfiguration',
    slaHours: 48,
  },
  {
    name: 'CSRF Protection Desativado (.NET)',
    queryPattern: '"ValidateAntiforgeryToken(false)" OR "[IgnoreAntiforgeryToken]"',
    category: 'Configuração Incorreta',
    severity: 'medium',
    description: 'Proteção contra CSRF desativada em controllers .NET',
    externalId: 'OWASP A05:2021',
    externalLink: 'https://owasp.org/Top10/A05_2021-Security_Misconfiguration/',
    reference: 'OWASP Top 10 2021 - A5: Security Misconfiguration',
    slaHours: 48,
  },
  {
    name: 'SSL/TLS Validation Disabled (.NET)',
    queryPattern: '"CertificateValidationCallback" AND "return true;"',
    category: 'Configuração Incorreta',
    severity: 'high',
    description: 'Validação de certificado SSL/TLS desabilitada em .NET',
    externalId: 'OWASP A05:2021',
    externalLink: 'https://owasp.org/Top10/A05_2021-Security_Misconfiguration/',
    reference: 'OWASP Top 10 2021 - A5: Security Misconfiguration',
    slaHours: 24,
  },
  {
    name: 'SSL/TLS Validation Disabled (Node.js)',
    queryPattern: '"rejectUnauthorized: false"',
    category: 'Configuração Incorreta',
    severity: 'high',
    description: 'Validação de certificado SSL/TLS desabilitada em Node.js',
    externalId: 'OWASP A05:2021',
    externalLink: 'https://owasp.org/Top10/A05_2021-Security_Misconfiguration/',
    reference: 'OWASP Top 10 2021 - A5: Security Misconfiguration',
    slaHours: 24,
  },

  // 4. XSS
  {
    name: 'DOM-based XSS (innerHTML)',
    queryPattern: 'ext:js OR ext:ts AND "innerHTML = "',
    category: 'Cross-Site Scripting (XSS)',
    severity: 'high',
    description: 'Injeção de HTML via innerHTML sem sanitização',
    externalId: 'OWASP A03:2021',
    externalLink: 'https://owasp.org/Top10/A03_2021-Injection/',
    reference: 'OWASP Top 10 2021 - A3: Injection (XSS)',
    slaHours: 24,
  },
  {
    name: 'DOM-based XSS (document.write)',
    queryPattern: 'ext:js AND "document.write("',
    category: 'Cross-Site Scripting (XSS)',
    severity: 'high',
    description: 'Injeção de HTML via document.write sem sanitização',
    externalId: 'OWASP A03:2021',
    externalLink: 'https://owasp.org/Top10/A03_2021-Injection/',
    reference: 'OWASP Top 10 2021 - A3: Injection (XSS)',
    slaHours: 24,
  },
  {
    name: 'XSS (Html.Raw) - ASP.NET MVC',
    queryPattern: 'ext:cs AND "Html.Raw("',
    category: 'Cross-Site Scripting (XSS)',
    severity: 'high',
    description: 'Renderização de HTML sem escape em ASP.NET MVC',
    externalId: 'OWASP A03:2021',
    externalLink: 'https://owasp.org/Top10/A03_2021-Injection/',
    reference: 'OWASP Top 10 2021 - A3: Injection (XSS)',
    slaHours: 24,
  },
  {
    name: 'XSS (dangerouslySetInnerHTML) - React',
    queryPattern: 'ext:jsx OR ext:tsx AND "dangerouslySetInnerHTML"',
    category: 'Cross-Site Scripting (XSS)',
    severity: 'high',
    description: 'Injeção de HTML com dangerouslySetInnerHTML no React',
    externalId: 'OWASP A03:2021',
    externalLink: 'https://owasp.org/Top10/A03_2021-Injection/',
    reference: 'OWASP Top 10 2021 - A3: Injection (XSS)',
    slaHours: 24,
  },

  // 5. Insecure Deserialization
  {
    name: 'Insecure Deserialization - .NET (BinaryFormatter)',
    queryPattern: 'ext:cs AND ("BinaryFormatter.Deserialize" OR "NetDataContractSerializer" OR "TypeNameHandling.All")',
    category: 'Deserialização Insegura',
    severity: 'critical',
    description: 'Deserialização insegura com BinaryFormatter ou NetDataContractSerializer em .NET',
    externalId: 'OWASP A08:2021',
    externalLink: 'https://owasp.org/Top10/A08_2021-Software_and_Data_Integrity_Failures/',
    reference: 'OWASP Top 10 2021 - A8: Software and Data Integrity Failures',
    slaHours: 4,
  },
  {
    name: 'Insecure Deserialization - Java (ObjectInputStream)',
    queryPattern: 'ext:java AND ("ObjectInputStream" AND "readObject")',
    category: 'Deserialização Insegura',
    severity: 'critical',
    description: 'Deserialização insegura com ObjectInputStream em Java',
    externalId: 'OWASP A08:2021',
    externalLink: 'https://owasp.org/Top10/A08_2021-Software_and_Data_Integrity_Failures/',
    reference: 'OWASP Top 10 2021 - A8: Software and Data Integrity Failures',
    slaHours: 4,
  },
  {
    name: 'Insecure Deserialization - Python (pickle)',
    queryPattern: 'ext:py AND "pickle.loads"',
    category: 'Deserialização Insegura',
    severity: 'critical',
    description: 'Deserialização insegura com pickle.loads em Python',
    externalId: 'OWASP A08:2021',
    externalLink: 'https://owasp.org/Top10/A08_2021-Software_and_Data_Integrity_Failures/',
    reference: 'OWASP Top 10 2021 - A8: Software and Data Integrity Failures',
    slaHours: 4,
  },
  {
    name: 'Insecure Deserialization - Python (yaml.load)',
    queryPattern: 'ext:py AND "yaml.load("',
    category: 'Deserialização Insegura',
    severity: 'critical',
    description: 'Deserialização insegura com yaml.load (sem SafeLoader) em Python',
    externalId: 'OWASP A08:2021',
    externalLink: 'https://owasp.org/Top10/A08_2021-Software_and_Data_Integrity_Failures/',
    reference: 'OWASP Top 10 2021 - A8: Software and Data Integrity Failures',
    slaHours: 4,
  },
  {
    name: 'Insecure Deserialization - PHP (unserialize)',
    queryPattern: 'ext:php AND "unserialize("',
    category: 'Deserialização Insegura',
    severity: 'critical',
    description: 'Deserialização insegura com unserialize em PHP',
    externalId: 'OWASP A08:2021',
    externalLink: 'https://owasp.org/Top10/A08_2021-Software_and_Data_Integrity_Failures/',
    reference: 'OWASP Top 10 2021 - A8: Software and Data Integrity Failures',
    slaHours: 4,
  },

  // 6. SSRF
  {
    name: 'SSRF - C# (HttpClient sem BaseAddress)',
    queryPattern: 'ext:cs AND "HttpClient(" AND NOT "BaseAddress"',
    category: 'Server-Side Request Forgery (SSRF)',
    severity: 'high',
    description: 'Requisições HTTP dinâmicas sem base URL controlada, potencial SSRF',
    externalId: 'OWASP A10:2021',
    externalLink: 'https://owasp.org/Top10/A10_2021-Server-Side_Request_Forgery/',
    reference: 'OWASP Top 10 2021 - A10: Server-Side Request Forgery',
    slaHours: 24,
  },
  {
    name: 'SSRF - Python (requests.get com entrada do usuário)',
    queryPattern: 'ext:py AND "requests.get(" AND ("request.args" OR "request.form")',
    category: 'Server-Side Request Forgery (SSRF)',
    severity: 'high',
    description: 'Requisições HTTP com entradas do usuário, potencial SSRF',
    externalId: 'OWASP A10:2021',
    externalLink: 'https://owasp.org/Top10/A10_2021-Server-Side_Request_Forgery/',
    reference: 'OWASP Top 10 2021 - A10: Server-Side Request Forgery',
    slaHours: 24,
  },
  {
    name: 'SSRF - PHP (file_get_contents com $_GET)',
    queryPattern: 'ext:php AND "file_get_contents(" AND "$_GET"',
    category: 'Server-Side Request Forgery (SSRF)',
    severity: 'high',
    description: 'Leitura de arquivos/URLs com entradas do usuário, potencial SSRF',
    externalId: 'OWASP A10:2021',
    externalLink: 'https://owasp.org/Top10/A10_2021-Server-Side_Request_Forgery/',
    reference: 'OWASP Top 10 2021 - A10: Server-Side Request Forgery',
    slaHours: 24,
  },

  // 7. Broken Access Control
  {
    name: 'Path Traversal - C# (File.ReadAllText com input do usuário)',
    queryPattern: 'ext:cs AND "File.ReadAllText(" AND ("Request.QueryString" OR "Request.Form")',
    category: 'Path Traversal',
    severity: 'high',
    description: 'Leitura de arquivos usando caminhos fornecidos pelo usuário, potencial Path Traversal',
    externalId: 'OWASP A01:2021',
    externalLink: 'https://owasp.org/Top10/A01_2021-Broken_Access_Control/',
    reference: 'OWASP Top 10 2021 - A1: Broken Access Control',
    slaHours: 24,
  },
  {
    name: 'Path Traversal - Java (new File com request.getParameter)',
    queryPattern: 'ext:java AND "new File(" AND "request.getParameter"',
    category: 'Path Traversal',
    severity: 'high',
    description: 'Leitura de arquivos com entradas do usuário, potencial Path Traversal',
    externalId: 'OWASP A01:2021',
    externalLink: 'https://owasp.org/Top10/A01_2021-Broken_Access_Control/',
    reference: 'OWASP Top 10 2021 - A1: Broken Access Control',
    slaHours: 24,
  },
  {
    name: 'Path Traversal (Relative Path) - Busca Geral',
    queryPattern: '"../" OR "..\\\\"',
    category: 'Path Traversal',
    severity: 'high',
    description: 'Uso de caminhos relativos para acesso a arquivos, potencial Path Traversal (deve ser combinado com APIs de leitura)',
    externalId: 'OWASP A01:2021',
    externalLink: 'https://owasp.org/Top10/A01_2021-Broken_Access_Control/',
    reference: 'OWASP Top 10 2021 - A1: Broken Access Control',
    slaHours: 24,
  },
  {
    name: 'Backdoor / Hardcoded Admin Credentials',
    queryPattern: '"test_password" OR "bypass_auth" OR "debug_admin"',
    category: 'Broken Access Control',
    severity: 'critical',
    description: 'Possíveis backdoors ou credenciais de teste hardcoded',
    externalId: 'OWASP A01:2021',
    externalLink: 'https://owasp.org/Top10/A01_2021-Broken_Access_Control/',
    reference: 'OWASP Top 10 2021 - A1: Broken Access Control',
    slaHours: 4,
  },
  {
    name: 'AllowAnonymous em Controllers (C#)',
    queryPattern: 'ext:cs AND "[AllowAnonymous]"',
    category: 'Broken Access Control',
    severity: 'high',
    description: 'Rotas públicas sem autenticação - verificar se são sensíveis',
    externalId: 'OWASP A01:2021',
    externalLink: 'https://owasp.org/Top10/A01_2021-Broken_Access_Control/',
    reference: 'OWASP Top 10 2021 - A1: Broken Access Control',
    slaHours: 24,
  },
];

async function updatePatterns() {
  console.log('🚀 Conectando ao MongoDB...');
  await connectToDatabase();

  console.log(`🔄 Processando ${PATTERNS.length} padrões...`);
  
  let created = 0;
  let updated = 0;

  for (const pattern of PATTERNS) {
    // Tenta encontrar pelo nome ou queryPattern (para evitar duplicatas)
    const existing = await VulnerabilityPattern.findOne({
      $or: [
        { name: pattern.name },
        { queryPattern: pattern.queryPattern }
      ]
    });

    if (existing) {
      // Atualiza os campos (mantendo dados existentes que não estão no padrão)
      await VulnerabilityPattern.updateOne(
        { _id: existing._id },
        { 
          $set: {
            name: pattern.name,
            queryPattern: pattern.queryPattern,
            category: pattern.category,
            severity: pattern.severity,
            description: pattern.description,
            externalId: pattern.externalId,
            externalLink: pattern.externalLink,
            reference: pattern.reference,
            slaHours: pattern.slaHours,
            enabled: true,
          }
        }
      );
      updated++;
    } else {
      // Cria novo
      const newPattern = new VulnerabilityPattern({
        ...pattern,
        enabled: true,
      });
      await newPattern.save();
      created++;
    }
  }

  console.log(`✅ Processamento concluído: ${created} criados, ${updated} atualizados.`);
  process.exit(0);
}

updatePatterns().catch((error) => {
  console.error('❌ Erro ao atualizar padrões:', error);
  process.exit(1);
});